### ISSUE TITLE
hello.tsx vs Hello.tsx

### ISSUE THREAD

**Issue by kellywoo** [frontStudySession/sam#2]
https://github.com/frontStudySession/sam/blob/b29c73c4c402ceae116c00f2cafc5361e74b035a/src/App.tsx#L2
실제 파일 이름이 app/hello.tsx 라고 되어있습니다.
윈도우 사용시 대소문자 구분 주의해주세요. 맥에서는 에러발생됩니다.

**Comment by samankey** [comment]
넵 확인했습니다. 감사합니다!
